apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudsentinel-runtime
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cloudsentinel-secret-store
  target:
    name: cloudsentinel-runtime
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        MYSQL_HOST: mysql.cloudsentinel-data.svc.cluster.local
        MYSQL_PORT: "3306"
        MYSQL_DATABASE: cloudsentinel_staging
        MYSQL_USER: cloudsentinel_staging
        MYSQL_PASSWORD: "{{ .mysqlPassword }}"
        REDIS_HOST: redis.cloudsentinel-data.svc.cluster.local
        REDIS_PORT: "6379"
        REDIS_PASSWORD: "{{ .redisPassword }}"
        JWT_SECRET: "{{ .jwtSecret }}"
        ALERTMANAGER_WEBHOOK_TOKEN: "{{ .webhookToken }}"
        BOOTSTRAP_USER_USERNAME: "{{ .bootstrapUsername }}"
        BOOTSTRAP_USER_PASSWORD: "{{ .bootstrapPassword }}"
        MIGRATION_DATABASE_URL: "mysql://cloudsentinel_staging_migrate:{{ .migrationPassword }}@tcp(mysql.cloudsentinel-data.svc.cluster.local:3306)/cloudsentinel_staging"
  data:
    - secretKey: mysqlPassword
      remoteRef: {key: cloudsentinel-data-credentials, property: MYSQL_STAGING_PASSWORD}
    - secretKey: migrationPassword
      remoteRef: {key: cloudsentinel-data-credentials, property: MYSQL_STAGING_MIGRATION_PASSWORD}
    - secretKey: redisPassword
      remoteRef: {key: cloudsentinel-data-credentials, property: REDIS_PASSWORD}
    - secretKey: jwtSecret
      remoteRef: {key: cloudsentinel-staging-app, property: JWT_SECRET}
    - secretKey: webhookToken
      remoteRef: {key: cloudsentinel-staging-app, property: ALERTMANAGER_WEBHOOK_TOKEN}
    - secretKey: bootstrapUsername
      remoteRef: {key: cloudsentinel-staging-app, property: BOOTSTRAP_USER_USERNAME}
    - secretKey: bootstrapPassword
      remoteRef: {key: cloudsentinel-staging-app, property: BOOTSTRAP_USER_PASSWORD}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudsentinel-registry
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cloudsentinel-secret-store
  target:
    name: cloudsentinel-registry
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ .dockerconfigjson }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: cloudsentinel-registry
        property: .dockerconfigjson
