apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudsentinel-production
resources:
  - ../../base
  - namespace.yaml
  - hpa.yaml
replicas:
  - name: cloudsentinel-api
    count: 3
  - name: cloudsentinel-worker
    count: 3
patches:
  - path: lab-data-patch.yaml
  - path: app-node-patch.yaml
images:
  - name: cloudsentinel-api
    newName: crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-api
    digest: sha256:b2f919d2d148cd988d6ccf698833f6dd3a6fd4604e25a26719bc52cd11d4410b
  - name: cloudsentinel-worker
    newName: crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-worker
    digest: sha256:78b34086c463178daa11c6f1306f6787900ab3c7bf802b03b9d2b553f5d31865
  - name: cloudsentinel-migrate
    newName: crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-migrate
    digest: sha256:03158c8cadfcb167b00463462c7cf8bf132505a35da78eb51487a854d7127b9f
  - name: cloudsentinel-web
    newName: crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-web
    digest: sha256:c578ab9e979a18630aa111eb9b3afc05d1d0b18e5ab903a04cdf371a7ab9f7b6
