apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - configmap.yaml
  - deployment-api.yaml
  - deployment-worker.yaml
  - deployment-web.yaml
  - service-api.yaml
  - service-worker.yaml
  - service-web.yaml
  - migration-job.yaml
  - pdb.yaml
  - networkpolicy.yaml
labels:
  - pairs:
      app.kubernetes.io/name: cloudsentinel
      app.kubernetes.io/part-of: cloudsentinel
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false
