apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudsentinel-staging
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: environment-patch.yaml
  - path: lab-data-patch.yaml
  - path: app-node-patch.yaml
images:
  - name: cloudsentinel-api
    newName: crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-api
    digest: sha256:4d762f0ca2c1443d511e17eca29eb4ac76ac9b06a519aeba01c0748431bdde91
  - name: cloudsentinel-worker
    newName: crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-worker
    digest: sha256:20b104772683b279a7dd94f41c40f62ab4948424e26ccfdfe29dd8e4d74c37b3
  - name: cloudsentinel-migrate
    newName: crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-migrate
    digest: sha256:b663611e656aa3c14445526ae5ab62890a0e0288262444c245a89ff46e7074c5
