apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudsentinel-staging
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: environment-patch.yaml
  - path: lab-data-patch.yaml
  - path: app-node-patch.yaml
images:
  - name: cloudsentinel-api
    newName: crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-api
    digest: sha256:e2a36bc65f23d8fb009250c477ad5a08c2e8d88c1357e59ac1ebbbbfb4f5029e
  - name: cloudsentinel-worker
    newName: crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-worker
    digest: sha256:2f3cd01435315a71bda080e33a1b7b197058375e29a5463c3427ec0408006c72
  - name: cloudsentinel-migrate
    newName: crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-migrate
    digest: sha256:06b5f7c8bbf831d76fb2605b9f8e54d580ebfc2c508468a92006b82399d82e35
  - name: cloudsentinel-web
    newName: crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-web
    digest: sha256:e309dfea21b04975d0fefe809259fea31b6a32f06ace25c69113e5f03c4c8b0d
