apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudsentinel-monitoring-runtime
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cloudsentinel-secret-store
  target:
    name: cloudsentinel-monitoring-runtime
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        ALERTMANAGER_WEBHOOK_TOKEN: "{{ .webhookToken }}"
        GRAFANA_ADMIN_USER: "{{ .grafanaUser }}"
        GRAFANA_ADMIN_PASSWORD: "{{ .grafanaPassword }}"
  data:
    - secretKey: webhookToken
      remoteRef:
        key: cloudsentinel-monitoring
        property: ALERTMANAGER_WEBHOOK_TOKEN
    - secretKey: grafanaUser
      remoteRef:
        key: cloudsentinel-monitoring
        property: GRAFANA_ADMIN_USER
    - secretKey: grafanaPassword
      remoteRef:
        key: cloudsentinel-monitoring
        property: GRAFANA_ADMIN_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudsentinel-registry
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cloudsentinel-secret-store
  target:
    name: cloudsentinel-registry
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ .dockerconfigjson }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: cloudsentinel-registry
        property: .dockerconfigjson
