apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage.yaml
  - external-secrets.yaml
  - rbac.yaml
  - prometheus-config.yaml
  - prometheus-rules.yaml
  - prometheus.yaml
  - alertmanager-config.yaml
  - alertmanager.yaml
  - grafana-config.yaml
  - grafana.yaml
  - grafana-public.yaml
  - metrics-server.yaml
  - networkpolicy.yaml
labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/part-of: cloudsentinel
    includeSelectors: false
images:
  - name: cloudsentinel-prometheus
    newName: crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-prometheus
    digest: sha256:442634af681c5988a3ccbd4c6e6ab57e077dc89eead4a31e2abf410501874a92
  - name: cloudsentinel-alertmanager
    newName: crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-alertmanager
    digest: sha256:82c38dcc97cd0fbf5d5e31ddfb304dbb3a6e411194477de5de82ec71b328bb40
  - name: cloudsentinel-grafana
    newName: crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-grafana
    digest: sha256:3625fdfa3cab904abdf9faaff8f40de0639b456ac5c5d322964fe705051d5455
  - name: cloudsentinel-metrics-server
    newName: crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-metrics-server
    digest: sha256:4a4376379ab80d3e1fd5edbf8c3ddcc0b9be8ccb56167e4f8c9423e5e11b0cfe
