apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudsentinel-runtime
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cloudsentinel-secret-store
  target:
    name: cloudsentinel-runtime
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: REPLACE_PRODUCTION_RUNTIME_SECRET_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudsentinel-registry
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cloudsentinel-secret-store
  target:
    name: cloudsentinel-registry
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: REPLACE_PRODUCTION_REGISTRY_SECRET_KEY
