apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../lab-staging
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/nodeSelector
        value:
          workload.cloudsentinel.io/app: "true"
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cloudsentinel-web
    patch: |-
      - op: replace
        path: /spec/template/spec/nodeSelector
        value:
          workload.cloudsentinel.io/edge: "true"
  - target:
      group: batch
      version: v1
      kind: Job
    patch: |-
      - op: replace
        path: /spec/template/spec/nodeSelector
        value:
          workload.cloudsentinel.io/app: "true"
images:
  - name: crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-api
    newName: crpi-1s64ln3ptbvgkqof.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-api
  - name: crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-worker
    newName: crpi-1s64ln3ptbvgkqof.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-worker
  - name: crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-migrate
    newName: crpi-1s64ln3ptbvgkqof.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-migrate
  - name: crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-web
    newName: crpi-1s64ln3ptbvgkqof.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-web
