apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudsentinel-production
resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
  - hpa.yaml
replicas:
  - name: cloudsentinel-api
    count: 3
  - name: cloudsentinel-worker
    count: 3
images:
  - name: cloudsentinel-api
    newName: crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-api
    digest: sha256:REPLACE_API_DIGEST
  - name: cloudsentinel-worker
    newName: crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-worker
    digest: sha256:REPLACE_WORKER_DIGEST
  - name: cloudsentinel-migrate
    newName: crpi-1s64ln3ptbvgkqof-vpc.cn-beijing.personal.cr.aliyuncs.com/cloudsentinel0306/cloudsentinel-migrate
    digest: sha256:REPLACE_MIGRATE_DIGEST
