apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudsentinel-data-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cloudsentinel-secret-store
  target:
    name: cloudsentinel-data-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: cloudsentinel-data-credentials
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudsentinel-registry
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cloudsentinel-secret-store
  target:
    name: cloudsentinel-registry
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ .dockerconfigjson }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: cloudsentinel-registry
        property: .dockerconfigjson
