apiVersion: v1
kind: Namespace
metadata:
  name: cloudsentinel-data
  labels:
    environment.cloudsentinel.io/name: lab
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
